// Generated by Dagger (https://google.github.io/dagger).
package com.a15acdhmwbasicarch.presentation.mainActivity;

import com.a15acdhmwbasicarch.data.PostsInfoRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class MainViewModel_Factory implements Factory<MainViewModel> {
  private final Provider<PostsInfoRepository> repositoryProvider;

  public MainViewModel_Factory(Provider<PostsInfoRepository> repositoryProvider) {
    this.repositoryProvider = repositoryProvider;
  }

  @Override
  public MainViewModel get() {
    return provideInstance(repositoryProvider);
  }

  public static MainViewModel provideInstance(Provider<PostsInfoRepository> repositoryProvider) {
    return new MainViewModel(repositoryProvider.get());
  }

  public static MainViewModel_Factory create(Provider<PostsInfoRepository> repositoryProvider) {
    return new MainViewModel_Factory(repositoryProvider);
  }

  public static MainViewModel newMainViewModel(PostsInfoRepository repository) {
    return new MainViewModel(repository);
  }
}
